void main(){
	printf("                                                                                                                                                                                                                                        
.'''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
;:::::::::cccccclllllllllllllooooooooooooooddddddddddddddddxxxxdddddddddddddddddddddddoooooooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllllllllllllllllllllcccccccccccclccclcccclllccccccccccccllcclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooollllllllllolloo
;;;:::::::ccccccllllllllllllooooooooooooooddddddddddxxxxxxxxxxxxxxxxxddxddddddddddddddddddddooooddooooooooooooooooooooooooollllllllllllcccccccccccccclllllllllllllllllllllllllcccc:::::::::::ccccccccccccccccccc::c::::cc:ccccccllcccllcclccccccclllllllcclccccccccccccccllllllllllllllllllcclccccclllllllll
;;::::::::ccccclllllllllloooooooooooooooddddddddxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxddddddddddddddooooooooooooooooooooool:,''...'''.............''',,,;:cllllllllllllllllc:;,'.............',;;::ccccccccccc;'...........';cccccccccccccccccccclllllllcc:,'...........',:clllllllllllc;'''.......'';clllll
:::::::::ccccclllllllloooooooooooooooddddddddxxxxxxxxxxkkkxxxdddxxxxxxkkkkkkkxxxxxxxxxxdddddddddddddooddddddddddooooooooolc' .,;;;;;;;;;;;;;;;;;;;,,''.....';cllllllllllc:,....';:cllooollc:;'....';:cccccccc:. .,;;;;;;;,. .:ccccccccccccccccccclllcllcc:' .,;;;;;;;;;,. ':ccllllllllc:. .;;;;;;;;. .;cllll
::::::ccccccclllllllloooooooooooooodddddddddxxxxxxkkkkkxddlllooodddddddxxkOOOOOOxxxkxxdddddddddddddddddddddddddddddddoooolc. ;0XXXXXXXXXXXXXXXXXXXXXK000kd:...;cllllllc;'..,lxOKXXXXXXXXXXXNXKOxl,...,:ccccc:;. ;0XXXXXXXO, .,;:ccccccccccccccccccccclcc:,..lKXXXXXXXXXKo..';cccllllllc;. cKXXXXXXXl .,::ccl
ccccccccccccllllllloooooooooooooodddddddddxxxxxxkkkkxddolllcllooooodddddxxkkO0KK0Okxxxxxxxxxddddddddddddddddddddddddddddolc. ;0XXXXXXXXXXXXXXXXXXXXXXXXXXXXO:..,:cllc:'..ckKXXXXXXXXXXXXXXXXXXXXXKkc...;:ccc:;. ;0NXXXXXX0,  ...,:ccccccccccccccccccccc:;. :0XXXXXXXXXXXKc. ..;:clllllc;. cKXXXXXXXl  ...,:c
cccclllllllllllllooooooooooodddddddddddxxxxxxxxkkkkxocc::llllllloddxxdddodxkO000KKKOkxxxxxxxxdddddddddddddxxxxxxxxxxxxxddoc' ;0XXXXXXXKd::::::ccokKXXXXXXXXX0:  .;::,..;kXXXXXXXXXKOxddxkOKXXXXXXXXXk;..'::c:;. ;0XXXXXXXO,     .::cccccccccccccccccccc;. ,OXXXXXKOKXXXXXO;   .;cclllcc;. cKXXXXXXXl     .;c
lllllllllllllllooooooooooooodddddddddxxxxxxxxkkkkkocccc:ccccccllc;cooloooldxxkO00KXX0kxxxxxxxxxddddddddddxxxxxxxxxxxxxxxdol' ,0XXXXXXX0;         .;OXXXXXXXXXx.   ....cKXXXXXXXXkc'.     .'lOXXXXXXXXKc. .,::;. ;0XXXXXXX0,     .;:ccccccccccccccccccc;' .xXXXXXXo,xXXXXXXk.   .;cccccc;. :KXXXXXXXc     .;c
llllllllllllloooooooooooooodddddddddxxxxxxxkkkkkkdcc::ccc::::cl;...;:;ccllodxxkkO0KXXKOxxkxxxxdddddddddxxxxxxxxxxxxxxxxxxdl' ;0XXXXXXX0;           lXNXXXXXXXk.      :KXXXXXXXKl.           .oKNXXXXXXK:  ..,,. ;0XXXXXXX0,     .;:cccccccccccccccccc:,..lXXXXXXO, ;0XXXXXXo.   ':ccccc;. ,OXXXXXX0;     .;:
llllloooooooooooooooooooooddddddddxxxxxxxxkkkkkkkl::ccccc:::clc'....,ldoloodxkOOO000KXX0kxxxxxddddddddxxxxxxxxxxxkkkkkkkxdl' ;0XXXXXXX0;          .dXNNXXXXXXd.     .kNXXXXXXKo.         ... .oXXXXXXXXk.   .'. ;0XXXXXXX0,     .;:ccccccccccccccccc:,. :0XXXXXKc  .oXXXXXXKc   .,:cccc:' .kXXXXXXO'     .;:
loooooooooooooooooooooooddddddddxxxxxxxxkkkkkkkkxl:c::c:;,;cc:c:,,,:x00OOOOOOOOOOKXKKKXXOxxxxxxddddddxxxxxxxxxxxxkkkkkkkkdl' ;0XXXXXXX0:     ...':kXXXXXXXXXk'      :KXXXXXXXO,       .,;::,. ,ONXXXXXXK:    .. ;0XXXXXXX0,     .;:cccccccccccccccc:;. ,OXXXXXXx.   'kXXXXXXO;   .,:ccc:,..oXXXXXXd.     .;c
oooooooooooooooooooooooddddddddxxxxxxxxxkkkkkkkOko:::;:;;;;;,,;cllodxkOOOO00000OOOKXXXXXKOxxxxdddddddxxxxxxxxxxxxkkkkkkkkdo, ;0XXXXXXXXOkkkkkkO0KXNXXXXXXX0l.       lXXXXXXXXx.     .':clcc:' .kXXXXXXXXl       ;0XXXXXXX0,     .;:ccccccccccccccc:;. .xXXXXXX0;     :KXXXXXXk.   .;:cc:;. cXXXXXKc      ':c
oooooooooolloooooooooodddddxxdxxxxxxxxxkkkkkkkkkOxl:;,,'','';:::ccllodxkkkO000O0000KXXXXNKkdxxdddddddxxxxxxxxxxxkkkkkkkkxdo, ;0XXXXXXXXXXXXXXXXXXXXK0kxxo;.        .oXXXXXXXXd.     .:llllc:, .xXXXXXXXXl       ;0NXXXXXX0,     .;:cccccccccccccc::'..lXNXXXXXo.     .dXXXXXXXo.   ';:c:;. ,0XXXN0;     .,:c
ooooooollllllooooooodddddddxxxxxxxxxxxkkkkkkkkkkOxl,,''',,;;;;;;:::ccclodxxkO0OOO00KKXXXXX0xddxxxddddxxxxxxxxxxxkkkkkkkkxdl' ;0XXXXXXXXkddxOKXXXXKOo:..             cXXXXXXXXx.    .,clooll:' .kXXXXXXXXc       ;0XXXXXXX0,     .;:ccccccccccccc::,. :0NXXXXXk'       ,OXXXXXXKc   .,:::;' .kXXXXk'     .,:c
lllllllllllllooooooooddddddxxxxxxxxxkkkkkkkkkkOxc,.',,;:::::;;;;;:::::::clccldkkk0000XXXXNNKkdxxxddddddddxxxxxxxxkkkkkkxxdl' ;0XXXXXXX0;   .,dKXXXXX0kxd:.      ... ;0XXXXXXXO,    .;cloolc:. ;0XXXXXXX0;       ;0XXXXXXX0,     .;:ccccccccccccc:,. ,OXXXXXXKl.........oXXXXXXXO;   .,;::,..oXXXXd.     .;:c
lllllllllllllooooooooddddddxxxxxxxxxkkkkkkkkkdl,...',:::c:::;;;;;;;;;;;;;;::cldxxxkOOO0KKXXXXOxdddddddddddddxxxxxxxxxxxxxdl' ;0XXNXXXX0;     .c0XXXXXXXXKk;  ..;::,..xXXXXXXXXo.   .;clllc:'..dXXXXXXXXx.       ;0XXXXXXX0,     .,;:::::::::::::;. .xXXXXXXXX0OkkkkkkkO0XXXXXXXXk'   .,;:,. .;:;;.      ';:c
llcccclllllllooooooooodddddxxxxxxxxxxkkkkkko:,''',:codoollc::;;;;;;;;;;;;;:clodxxxkkkkO0O0KXXXKkxddddddddddddddddxxxxxxxdol' ;0XXXXXXX0;       :0XXXXXXXXXKl. .;cc:. ;0XXXXXXXKd.   .;;;;'...oKXXXXXXX0;        ;0XXXXXXX0,      .............,;'..lKXXXXXXXXXXXXXXXXXXXXXXXXXXXXd.   .,,.             .,::c
cccccllllllllooooooooddddddxxxxxxxxxxxkkkkl''',:oxkkkkxdolcc::;;;;,,,,,,;;::::loooxxkkOOO0KKKKXX0kxddddddddddddddddddddddoc' ;0XXXXXXX0;     .. ;OXXXXXXXXXKo. .,:c;..:0XXXNXXXXOo;......';oOXXXXXXXX0:         ;0XXXXXXXKdcccccccccccccccc;. ... :KXXXXXXXKKKKKKKKKKKKKKKXXXXXXXKc    .. .,::::::;.   .,::c
ccccclllllllllloooooodddddxxxxxxxxxxxxxxko'';cdkkkkkkkkkkxlc:::;;,,,,,,,,,;:::cooodxxkkkOOOO00000K0kkxxddddddddddddddddddoc' ;0XXXXXXX0;     .,. ,OXXXNXXXXXKo.  .:c;..'dKXXXXXXXXX0OkxkO0XXXXXXXXXKx'       .. ;0XXXXXXXXXXXXXXXXXXXXXXXXNk' .. ,OXXXXXXXk;.'..........':ONXXXXXX0;    . 'OXXXXXX0,  .';:cc
ccccclllllllloooooooodddddxxxxxxxxxxxxxxkdcoxkkkkkkxxxxkxxxdc;;;,,,'','',,,;:cloloddxxxxkkkkOOO0000OOOkkkxxxxxdddddoooodooc' ;0XXXXXXX0;     '::. 'kXXXXXXXXXXd.  .;c:,..;d0XXXXXXXXXXXXXXXXXXXXX0d;.       ... ;0XXXXXXXXXXXXXXXXXXXXXXXXXk'   .xXXXXXXXK:               lKXXXXXXXk'     'OXXXXXXO,   ..,::
ccccccllllllooooooooodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd:,,,,'','',,,,;:::lddoodddxxkkkkkkkkkOkkkOOOkkkxxxxxddddoooolc' ,OKKKKKKKO,     'clc' 'xKKKKKKKKK0o.  .:cc:,...:oxOKXXXXXXXXXXXKOko:.         .,,. ,OKKKKKKKKKKKKKKKKKKKKKKKKKx.   c0KKKKKKKo.               .xKKKKKKKKl.    'kKKKKKKO,     .;:
llllcclllllloooooooooodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc,,,'''''''',,:c::llloooddxxxxxxxxxxxxxxxkOOkkkxdxxxxxxxddoolc, .''''''''.      ,looc,..',''''''''.    .:lllc;'.. ..,;;:ccc::;,'.           .';::' .''''''''''''''''''''''''''.    .'''''''..      ..',,,,''. .''''''''.      .''''''.      .;:
lllllllllllooooooooooooddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl,,'',.','..,,;;:clllodddxdddooodddxxkxxxxkkxxkkkkkxxxkxxxdddoc;,,,.            ,lodolc;,,'.            .:looolc;'.                       .';cccc:,'''.                              .             ';::::::;,''..             ...           .;:
lllllllllllooooooooooooooodddddddddxxxxxxxxxxxxxxxxxxxxdxxdxxc,,.','''..,,',:cclooodddddddddxxxdxxxxxxdddxxxxxxxxxxxxxxdxkxdooolc'          .;lddddddool:..          .,lodddoolc;'..               ..';:cllllllcccc;.                            ...           .;:::::::::::;;'.          .',,.         .';:
llllllllloooooooooooooooooooooodddddddddddddddddddddddddddddxc','''',..',,';clolclloddddddxxxdddddxxxxxxxxddddxxxxxxxxxxxddddddddocc::::::::coodddddxdddolcc:::::::::clooddddddooolcc:;,,''''',,;;:ccccllllllllllllc:;;,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,,,,,,,,,,;::::c::::::::::;,,,,,,,,,,,;::;,,,,,,,,,;::c
llllllllllooooooooooooooooooooooodddddddddddddddddddddddddddd:'''''''',,,,,;cdxdlccclloooooooodxdooodxxxxxxddddxxxxxdddddxddooddddddddddooddddddddddxxxdddddddddddddoodddddddddddddooooooolllllllllllllllllllllllllllccccccccccccccccccccccccccc::cc:::::::::::::::::::::::::c:::::::::::::::::::::::::::::c
llllllllllooooolllllllllllllloooooooooooodddddddddddddddddddl;''',,'''',,,;coddxoc::::ccccccccloooddoldxdddddodddxxxxxxxxxdddoooodoodoodxxddddxddddxxxxxxddddddddddddddddddddddddddddddddoooooooooooollllllllllllllllllllllcccccccccccccccccccccccccccccc::::::::::::::::::::::::ccc:::::::::::::::::::::ccc
oooolloooooooolllllllllllllllllllloooooooooooooddoddddddddddl,'''''''',,;;c:,;clll:;;:ccccccccccllooolllodddoddolodxddddddxddxxdoddoddddoddxxdddddxxxxxxxdddddxxxddddddddddddddddddddddddddooooooooooolllllllllllllllllllllllllllllccccccccccccccccccccc::ccccc::::::::::::::::::cccccc::::::::::ccccc:::::c
looolllooloooollllllllllllllllllllllllooooooooooooooodooooodc'''''''',,;,,,,',;;;cc;;;::;;;;;::;;:ccccoolldolooollooddddooodoodddxkxdddddoooddxxxddxxxxxxddddddddddddddddddddddddddddddddddooooooooooooooooollllllllllllllllllllllccccccccccccccccc::::::::ccc:::::::::::::::::::::ccc::::::::::cccccc::::::
looollllllllollllllllcccccccccclllllllllllloooooooooooooooodc'''','',;;,,'''''''',,,,,;;,;,,,,;;,,;::clloccllcloolcclooooooolloodxkkxddoodxxdddxxxxxdxxxxddxxxxxxdddddddddddddddddddddddddddooooooooooooooooooollllllllllllllllllllccccccccccccccc:::::::::::::::::::::::::::::::::::::::::::cccccccccc::ccc
looolllllllllllllllcccccccccccccccccccllllllllllloooooooooooc,',,',,;;,,,,,,,''''''''',,,,,,,',,'',,;;;:c::ccccccc:coooolccloooodxdxxddxolldxxxxxxxxxxddddxxxxxxxxddddddddddddddddddddddddddoooooooooooooooooooolllllllllllllllllllcccccccccccc::::::::::c:::::::::::::::::::::::::::::::::::ccccccccccccccc
ooolllllllllllllllcccccc::::ccccccccccccclllllllllllooooooooc,',',,;;,,,,,,'''''''''''''''''''''',,,,,,,;;:::;;;:cc:llllc:cclllodddddddxxdoooddddxxxxxxxxxdxxddxxxddddddddddddddddddddddddddddddddooooooooooooooolllllllllllllllllccccccccccccc:cccc::::cc:::::::::::::::::::::::ccc:::::::::ccccccccccccccc
oolllllllllllllllccccc::::::::::::ccccccccclllllllllllllllloc,',,,;,,,,,,,,''''''''''''''''''''',''',,,,,,;;;;,,,:ccllccc:::::cloooooodxkxxkkxxddddxkkkkxxxxddxxxxxdddddddddddddddddddddddddddddddddooooooooooooooolllllllllllllllccccccccccccccccccc:cccc::::::::::::::::::::::ccccccc::::::ccccccccccccccc
olllllllllllllllccccc::::::::::::::::ccccccccllllllllllllolol;',,;;,,,,,,,,',''',,'''''','',,,,,,,,''',,,,,,,,,,,,,;;:::cc::;:cclooddoooddoxkkkxxxxdxxkkkOOkkkxdddddddddddddddddddddddddddoodddddddddddddooooooooooollllllllllccccccccccccccccccccc:::::cccc:::::::::::::::::::cccccccccccc:cccccccccccccccc
llllllllllllllllcccccc::::::::::::::::ccccccccllllllllllolloo:,,,,,,;,,,,,,,,''',,'','''',,,,,,,,;;,,,,,,,,,,,,,,,,'',,;;:;,,;;;;:lloooolloxdodddxkkxddddxkxkOkxxddddddddddddddddddddddooooooooddddddddddooooooooooolllllllllllclccccccccccccccccccccccccccc::::::::::::::cccccccccccccccccccccccccccccccccc
lllllllllllllllcccccccc::::::::::::::::ccccccccllllllllllllloc,,,,,,,,,,,,,,,,,''',,''''''',,,,,,,,,;;;;;;;;;;;;;;:;,'',,;;;;;;;;,,;cc::cldkxolllloxkkkxddxxxkkkkkxddddddddddddddddoooooooooooooooddddddooooooooooooolllllllllllllcccccccccccccccccccccccccccc:::::::::::ccccccccccccccccccccccccccccccccccc
lllllllllllllccccccccccccccc:::::::::::cccccccclllllllllllllol;,,,,'',,,,,,,,,,,''',''',''',,,,,,,,,,;;;;;;,,;:::ccllc::;'',,;;;;,,,;:::cclooolclllodkkkxdddooxkkOkxxddddddddddddooooooooooooooooooooooooooooooooooooolllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
lllllllllllccccccccccccccccccccc:::::::cccccccclllllllllllllloc;;,,,',,,',,,,,,''',,'',,,,,,,,,,,,,,,,,,,,,,,,,;;;;:cllodo:;;;,;,'';::;,;::ccllllccloxkxdddxkkxxkkOOOkxxdddddddooooooooooooooooooooooooooooooooooooooooollllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
llllllllllccccccccccccccccccccccccc::::ccccccccccclllllllllllol:;,,'''''',,,,,,,'',,,,,,,,,,'',,,,;,,;,,,;;;;;,,;;;;:clooxdoccllllc::::,',,;;;ccc::cldxoloodk0K0OkxxkkkOkxxddddodoooooooooooooooooooodddooooooooooooooooooolllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
llllllllcccccccccccccccccccccccccc:::::::::ccccccccllllllllllloc;,,,'''''',,'',,''',,,,,,,,,,,,,,,;;,,,,;;;;;;,,;;;;;;:clllolcclooollllc:,,,,,;::::;:odolooxxxk0K0OkkkkkOOkkxddddoooooooooooooooooooooooooooooooooooooooooooooolllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
llllllllcccccccccccccccccccccccccc:::::::::::cccccclllllllllllll:;'','',,',,',,,,,',,,;;,,,,,,,',,;;,,,;;;;;;;,;;;;;;;;;:cccllllcllccllollccc:;::cllloodoodxxddxkOOxxxxxkkkkkkxxdoooooooooooooooooooooooooooooooooooooooooooooooollllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccclllcccccccccccccccccccccccccccc:::::::::::cccccccllllllllllllc;,,'',,'',,,,,,,,,,,,,;;,,,,,;;;;;;,,;;;;,,,,,,;;;;c:;;;;;::ccllcc::ccccoooolllc:cllllloooooooollllok0OkkkkxxkOkxdoooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccc:::::::::::cccccccllllllllccllc:;;,''',,',,,,,,,,,,,,,,;,,,,,,;;;;;;;,,,,,,,,,;;,;:;;;;;,;;;:cllllc::;:::clccc:::::::::cc:ccccccllodxxkOkxxkxxkOOkxdooooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllcccccccclcccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccc::::::::::::cccccccccccccccccccc::;,'''''',',,,;;,,,;;;;;;;,,,,;,,,,,,,,;;,,,;;;;,,,,,;;;,,,;:c;,;:c:;;;;cccc;';::;;;:c:::;:ccccllllllldkO0kxdxxxkkkxxdooooooooooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccc::::::::::::::::ccccccccccccccccc::::;,''',,,,,,,,,,,,;;;,;;;;;;,,,,,,,,,;;;,,,;,;,,,,,,,;,,,,;:,',,;;;,,;;::c:'.',;:::;;;:::;:c:cclllllodxOOxdddddxkxkkkdoooooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccc
c::ccc:::::cccccccccccccccccccccc::::::::::::::::::ccccccccccccccc:::::;,'',,,,,,,,,,,,,,,,,,,,,;;,,,,,,,,;;;;;;,,,,,,,,;;;;;,,;;,'''',,,',,;:c:;'''',,;;;,,:c:;:clllcclddooxkkdodxdoxkxdxkkdoooodoooddoooooooooodddddddooooodddddooooooolllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccc
::::::::::::ccccccccccccccccccccc::::::::::::::::::::::::::::::c::::::::;,''',,,;;,,,,,,,;,,,,,,;;,;;;;;,,;;;,,,,,,,,,,,,;,,,,,,''''''',,'''',;;,,;,,,,,,;;;;;;cc::looolodxxxkkdlodoxxxkdddxkxddoddodooooooooooooddddddddoooodddddoooooooolllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccc
:::::::::::::ccccccccccccccccccccc::::::::::::::::::::::::::::::::::::::::,'',,,',,''''',;;;;,,,,;;;;;;;;;,,,,,,,,,,,,,,'''',''''''''''''''','''''',,;;;,,,,,,,,;;;;;:lc::ccllxkl:lodxxxdxkkxkkxxdoddoodooooooooodddddddddoodddddoooooooooollllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccc
::::::::::::::::ccccccccccccccccccc:::::::::;;;;:::::::::::::::::::::::::::;,',,,,,,,''',,,,,,,,,;;;,,,,,,,,,,,,,'',,,,,,',,,,,,,'''''''.'',,,'''''',,''''',,,,;,,,;;,,;;;;;:lxOd:,:llooddxkkxkkOOxdooooooooooooooooodddddoooddooooooooooooooooolllllllllllllllllllllllllllllllllllllllccccccccccccccccccccc
;;;;:::::::::::::cccccccccccccccccc:::::::::;;;;;;;;;;;:::::::::::::::::::c::;,,,,''',,,,'',,,,,;,,;,,,,,,,,,;,,,,,,,;,,'',,,,,,,'',,''''',,,'''''''',,,,,,,;::;::;;;::;::;;:cloddl;,;cloddxddxxkOOOkdoooooooooooooooooodooooooooooooooooooooooooooolllllllllllllllllllllllllllllllllllllcccccclllllcccccccc
;;;;;;;;;;:::::::cccccccccccccccccccc:::::::;;;;;;;;;;;;;;::::::::::::::c:::cc:;,',''',,,,,,',,,,,,;;;,,;;;;;;;;;;;,,,,'''''''',,,,,,,,'''',;,''''''''''''','',;::cc:;:ccc:::;;ccodc;;;;clllodddxxxkOxdooodoooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllllllllllllllllllllllcccccccc
;;;;;;;;;::::::cccccccccccccccccccccc:::::;;;;;;;;;;;;;;;;;;::::::::::::::::::cc:,',,,,,,;,,,,,,,,,,;:;;,,;;;;;,,,,,''','''''''''''',,,,,,'',''''''''''''''''''',;;;:::cc:;;:;,,;lxc,,;;;:cloolloddddddddoodddddoddooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllllcccccc
,;;;;;;;:::::ccccccccccccccccclcccccc:::::;;;;;,,,,,,,,;;;;;;;;:::::::::::cc:::::::;,,,,'',,,,,'''',,;,,,,,,,,,''''''',,,,'',,'''''.''''''''''''''''''''''''''...'',,,;::;;;;;;;:lo;','',,,;colcccloxxoloddddddddddddooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllllllllllllllllllllllllccc
;;;;;:::::::ccccccclllllllllllllccccc:::;;;;;,,,,,,,,,,,;;;;;;;;;;;;;:::::cccc:::::::::;;;,'',,,',,,,,,,'''''''',,'''''',,,,,,,,,,,''''...'''......''''''''''''....'''''',,;;;:clol;''....'',:lc::::ldkdoodxdoodddddddoooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllll
;;;;:::::::ccccccllllllllllllllllcccc::::;;;;;,,,,,,,,,,;;;;;;;;;;;;;:::::cccccc::::ccccccc:;;,,',,,,,,,,,,'''''',,,,'''''',,,,,,,,,,,,''''''.''''''''''''''''''''''''''',,;;;;;;;'',,''''...',cc:::::ldxdoooddoooddoddoooooooooooooooooooooooooooooooooooooolllllllllllllooolllllllllllllllllllllllllllllll
;;:::::::ccccccclllllllllllllllllccccc::::;;;;,,,,,,,,,,,;;;;;;;;;;;;:::::ccccllccccccccllllllc::;;,,,,,,;;;,,,'''',,,''''''''',,,,,;;;;;,''''''''''''''''''''','''''',''......'''...'..'''','';::;;;;;;cddolloodollloooooooooooooooooooooooooooooooooooooooooooolllllllllllolllllllllllllllllllllllllllllll
:::::::ccccccclllllllllllllllllllllcccc::::;;;;,,,,,,,,,,,,;;;;;;;;;;:::::ccccllllllccccccllllllllccc:::;;;;;;;,,,,'',,,,,,,,'''''''''',,''''''''''''''''.....................''.''....''....'',''',;,,,;:lollcclooollllodooooooooooooooooooooooooooooooooooooooollllllllllooooollllllllllllllllllllllllllll
:::::cccccccllllllllllllllllllllllccccc::::;;;;;,,,,,,,,,,,,;;;;;;;;;::::::cccclllooollccccccclcllllollllccc::::;;,,,,,,,,,,,,''.............................................''.........'.......''.''',;;,;loc:;;:ccodooooooooooooooooooooooooooooooooooooooooooollllllllloooooooooooooooolllllooooooollllll
cccccccccccclllllllllllllllllllllccccc:::::;;;;;,,,,,,,,,,,,,;;;;;;;;::::::cccclloooddddolccccclllllooollllcccccc::;;;::;;;;;,,'''........................................................'........'....'',::;;;,,,;:looddooooooooooooooooooooooooooooooooooooooooolllllllooooooooooooooooollooooooooooollll
cccccccccccclllllllllllllllllllccccccc::::;;;;;,,,,,,,,,,,,,,;;;;;;;;;:::::cccclllooddxxxxdolccccccllllllcclllllllllcccc:::ccccc:::;;;;;;,,;;;,,,;;,,,''''''''''...........................................''',,;;;,,;:cllooooooooooddollooooooooolloolllllllllloooollllllooooooooooooooooooooooooooooooolll
ccccccccccccclllllllllllllllcccccccccc:::;;;;;,,,,,,,,,,,,,,,,,,,,,;;;;:::::cccllloodddxxxxkxxdolcccccc:ccccclllllcclcccccccllc:::::::::::;;;;;::::::::::ccccc:::;;;;;;;,''.....................................',;;;;:ccccloooooooodxkkxdollooooolloolllllllllllllllllllloooooooooooooooooooooooooooooooool
ccccccccccccccclllllllllllccccccccccc::::;;;;;,,,,,,,,,,,,,,,,,,,,,;;;;;:::::ccclllooddddxxxxkkkxxddoc::;;;;;;;:::cccc::::::::::::;;;;;,;;,,;;;:::::cccclodddddoooolllllccc:::;;;;;;,,,,''.................',,''.'..,;;;:;;::cclllllloodxxxxxdoolllllllllllllllllllllllllloooooooooooooooooooooooooooooooooo
ccccccccccccccccccccccccccccccccccc::::::;;;;;,,,,,,,,,,,,,,,,,,,,,,,;;;;;:::cccclllooddddxxxkkkkkkkkxdolcc:;,'''',,;;;;;;;;;;;;;;,,,,'',,,,;:::::cloolooddoooooollllllccccccccllllllllllllllcllcccccccllccc:::;,'..........'',;;::::cccccclodxxxdollllllllllllllllllllllloooooooooooooooooooooooooooooooooo
cccccccccccccccccccccccccccccccc::::::::;;;;;;,,,,,,,,'',,,'''',,,,,,,;;;;;::::ccclloooddddxxxxkkkkkkkkkkkkd:'.......,;;;,,'''''''''''''',,,;:::cclodooooooooollllllllcccccc:::cccccccllllllllllllllllllllllllllcc:;;;,''.....'''..'''',,,;;;;:clodxxdollllllllllllllllolllooooooooooooooooooooooooooooooooo
cccccccccc::::cccccccccccc::::::::::::::;;;;,,,,,,,,,'''''''''',,,,,,,,;;;;;;:::cccclllooddddxxxxkkkkkkkxl:'......,;coolc:'.'.......''''',,;;:ccloooooooooolllllllllllllc::;::;;;;;:::cclllooodxddoollccccccccclllolccllloodollcc:;;''....'''''',,;:loddddollllllllllloolllooooooooooooooooooddddddddddddooo
:::::::::::::::::::::::::::::::::::::;;;;;;,,,,,''''''''''''''''',,,,,,,;;;;;;::::ccccloooddddxdxxxkdc:c:,,'.....'::::;,'.......  .';,,;,,:llclodxxxxxxxdoddxxdddddxxxkkxxxdoodolooodkkO0Ok00000KK0000Okxdoodxxdodl,......,;cldkOkkOOxdl:,'.......'''',:cloooolllllllllolllooloooooooooooooddddddddddddddddd
::::::::::::::::::::::::::::::::::;;;;;;;,,,,'''''''''''''''''''''''',,,,,,;;;;:::::::;;:::coddxOKKK000OO0OOkdddollc,.......';:cccldOO00OO0K00KKKXNNNNNNXXXNWWWNKKKKKK0OkO000Okkkkk0KKKKXXXKK0O0X0OKXKkollloodocclodxdooo:......'';:loxOXX0xdlc;,'.....''',;:cloooollllllllllloooooooooooooddddddddddddddddd
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,'''''''''''''''''''''''''',,,,,,,,;;;:codxddkOOOO0KOx0NNWWWNXKXXXXNNWNXKXK0OOxooOKNWNNXXXNWWWWWNXKXNNWNNNNXKXXNNNXXXXXNK0K00XXXKXNNNNX0O0XXXXKKXXKOkOXOxO00OxlcoodxkO00KK000KKKOxdol;.......,oOKKKKXKKOxdl;'..'''''';:cloooollllllllllooooooooooodddddddddddddddd
,,,;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;,,,,,'''''''''''''''''''''''''''',,,,,;:cllcclodxxOXXK0kkkxodxxkOk0KXNNNXXNNXKKXXNWXOdokKXNXK0kxkOO0XXKK0kxkOkkOkddddxO00K0OkO0KKKKNNNNNNXNNNXXNXXNNXNXXXKOO0Odc;cdO0kololllllll:codxkKWNNNX0xl;''....',;,,;cloxO0Oxl:,'..''''',;:clooollllllllllloooooooddddddddddddddd
,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;,,,,,''''''.'''''''''''''''',;:;;;;::;;:ccc:;;;;;;coxkkkxoc;;::ccc;:clldxk0KKOkxk0KK0dc::codxkkdxkdoxkkxkOkollllxxddoloodxkkkkxddxk0KXNNXKOO0kxkOxkKNNNNNWNXKXXX0kdddx0KOOdcc::cc:;;:coxOk0NNXNNNXKOd:'..........':kNWNKkdl:,'..''''',:ccllollllllllllooooddddddddddddddd
''''',,,'''''''',,,,,,,,,,,,,,,,,;,,,,'''''.........''';::cllldkOkxddxdl;;;::;,'','''''',;:clc;;,,'''',;cc:::cccloollldOkl;;,;;:oO00kkxdk0OOOkxoll::codddooddodkkxdxxxkOkk0K0xkKKOkOO0XK0XXNWWNXXNXXNNNKOOO00Oxook00000Okk0KXKKKKXXXXXXNKOkxoc;.......'codddxO0Okdl:,'..',,,,;:cccllcllllloooooodddddddddddd
'''''''''''''''''',,,,,,,,,,,,,,,,;;;:codxxdloooodxdddxkkkOOxxO000KKkxdl;'',,'''.''''..',;,',,,,;;;,..',;;;;,,,,,;;;;;:cc:;,,,;:cdxxooolcoxxollc;;;;,;:::::clcloocllccloloxxdxxdkO0OOO00KXKNWWNXXNN00XXKXXXXXKOxk0K0KNNNXKXNXKKkoxk0XNNXKKXNXK0kxo;,,'.......';cdO000kdl:,'..'',,;::;;::cllooooooodddddddddd
.'''''''''''''''''',,,,,,,,,,,;:lok0000KKXXNXK0000OOxlccc:;;;:ccclodoldo;'.''''''''''.....''',,'';;,',;;;,,,,,,;:;;;,,;;;;,,,;::;:cc:cc:;;::;;;;;,',''',;;,,;::::;;:;::::col::cc::coddxOKKKXNNNXOxO0KX0kOKXXKKXNNNNXKXNNNXKKK0O0OOOxxKNXXNNXK00O0XK0OOkoc,'....'',cdk0KKK0kdol:,,;:;:::::clllloooooooooodddd
.....''''..''''''''',,,,,,;:ccokkdddoodkOkxkkxdolccc;,'''.',,'';;,,;,,;:;;,,,,,,'',''''...,,;;,'',,,,,;;;,,,,,,;;;:::;;,,,;;,,;;,:ccccc:;;,''',,,,,,,',,,,,,'''''''''',,,;:c;,;;'',:ccldxkkOKXK0Oxxxddoclodddd0XNNNNNNNNXXXKK0OO0KOkxOXKXNNNNNX0KNK00KK00kxkkxxoc;;lx0kxk0KK0KKKOOkolodolclllllooooooooooooo
..............''''''';:looxOxl::ccc:;;;;:,',;;;,,,;,'',,,',;;,,''';;;;,',;;;;,,,'','.'''''''''''.',;,''''',,,,',,;:ccc;,,;;,;;;;;ccccol:;;,,,,;,,;;;;,,,''''.....''.....'.';,'.',;::;:lodxxxdddlloolc;,'',;;::coOXWWNNXXKKK0KKKKKK0Okkk0XNXXNNX0KXK00XXK0OOKXXKXXK00OOxlcokOkkkkOOKNXXNXKkdlcccllllooooooooo
...............',;coxdxxoloddc,,,;,,,,;;,'',,;,'..''''.'',,,,;,',;,',,,,''',,,''.''''',;::,,,'',,,,'''',;,',::;:::::::;,,,',;::::ccccll:::::;;::;;::;,,,,,,,'..',,'....'...','''',,''',;;;;;;:llc;'''''''',;;;;;:okOKK0000OxkKXXKXXK00OOXXKKXXK0KXXX000000XXKKXNNNNWNXOo:clxOOdoocd00XWWNXXKOxolcclllolooooo
'...........';clllxkdolccl:;:;,;,,,,,,,;,,,,,;;,''',,''''',,;,.';:;','',,''',;;;,,,,'';;;:;;;;,,,;;,,,;::;,,;;;::;;;;;,,;:;,;;;::::;;;::;,;;,',,,;:c:;;;;;;,,',,,,,'....'..',,,''''.....'...'',:c:'..''..',,;;;;;;;,;llloxOOkOOOkkOKKXXXXXX00KK00000OOOkkxOKXKXXKXNWNNKkdxO00KKkdoloox0XXKKXNNK0Oxolllllllll
'....'...,:ccccc:ccc;,;;::,'''''''''''''',;;'',,''',,,'.',,,;;,''',,,,,,;;,,;;;;;;;,,,;;,;;,;::;;,,,'',:c::::;;;,,,''''';::;;;,;c:;,,;;;;;;,'''',:;,;;;,,;;,,,,',,,,'..'''''',,'...........'''',,,....''.....'.......'',,,,:odddxdxKXXXNNNXXKK0OO0KKKXNXKOkOO0KKK0K00XX0O0KXKKXK0kclkO0XKKXNNNNNNNXK0Odoolll
..''',;:ll:clcc:;;,,,',,;:;,''..'''..'''''';;,''',''',,',;,'';;,,,,,,;,;;;,'',,',;;;,'''',,;::;;;;,,,',:c:c:;;;',::;,'',;::;;,,;;;;;;,,,;;;;,,,,,;,,;;:;,,,,;;,'''',,''','',;;,''...''''...'''''''..........................';loddodOXNXXXXXKK0OO00kxxOKXNXXKK0OkxxddOKKXNNNXKKXXK0kxxkOKKNWNK0KKKXXKXXKKOkO
,,;:looolcloc;;;,,,;;,,,,,'',,'''...'',,,,,,,,,'',''''.,;;,,',;,;;,,,;::;;,'';;,.',,'..'',;::;;;;;,,,,,,;;,,,;;;;:c:;,',::;,;:;,;;;;,'',,,;;;;;;,,,,,,;,'',,;,''',,;;,,,,,'''''''..''''''....'''''............'...............,clooodO000KKKKKOxxO0kdddoxOKKNWWNKkooodddkOO0XNXKKKXNXKKKKXNNNNXK0KXNNNNNNXOx
lodl::c:;;::;,,,,,,;;,,'...',;;;,''..''',;;:;,,,,,',,'',;;,'',,,,,;;,,;;;,,,;::;'''''''..,;;;;,;;,'',''',;,',;:::cccc;,',;;;;;,,;;;;,'''',;;;;;;::,,,''',,;;,,''',,;;;;;;,,,'''''''',''........'...'..........,,,'..............',,;clooxOkdldxxdxOOOkxxdoox0NNNNX0OkkxdoodxkKXK00KXXXXXXXXXXXXKOOKXXXXXXXX0
doc:;;;,,',,'.....','',''',,,',,''',,''',,;:;,,,;;,,,;;;,,''''',,,,,,,,,,'',;,'..''......',;;::::;,''',;::;;,,;;,;:cc;''';;,;;;;,,::::,.',:c:;;,,,''',,;;;,,''''',;,,,,,;::;,''''',,,,'',,''...'''''''''......',,'...................,;cldxxolllox0KK0OkxxddkKKXXNXXK0OOO00OkO0OkO00KXNX00KKK000KKKKXNXXXXXN
kc,;;;,,,,,'.....',,'''.',;;',,,'..,,''.',;;,,,,;;;::;;,,'..''''''',''',,,'',,,,''''....';;;;:c:;;;''';:ccc:,;:;,,;;;;;,,;,,,;;;,;:;;:;,;;;::;;,'',,,;;;,,,,,,,,,;;,'',,;;:;,''.'''''''',,,....'''''''''..............................';:clccc:;;:ox0KK0OO0XXKKXNNNX0OOO0000O0KK0O0XNNNKOk0XXKKKOkO0XNNXXXXN
'............................'.....................''.........................................'.........'''...........'...........'..................''............................................................................................';coolclooooooooolloddoooolool:;:llclocclooolllccclodoc:l
                         ");
}